controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    simplified.moveToRandomHoleOnGrid(myMole)
})
controller.player2.onButtonEvent(ControllerButton.A, ControllerButtonEvent.Pressed, function () {
    simplified.moveToRandomHoleOnGrid(myMole)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    info.changeScoreBy(1)
    simplified.moveToRandomHoleOnGrid(myMole)
    music.baDing.play()
    animation.runImageAnimation(
    myHammer,
    assets.animation`hammerAnimation`,
    50,
    false
    )
})
let myHammer: Sprite = null
let myMole: Sprite = null
scene.setBackgroundImage(assets.image`grid`)
myMole = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . e e e e e e e e e e e e . . 
    . e e e e e e e e e e e e e e . 
    e e e e e e f e e f e e e e e e 
    e e e e e e f e e f e e e e e e 
    e e e e e e e e e e e e e e e e 
    e e e e f e e e e e e f e e e e 
    e e e e e f 3 3 3 3 f e e e e e 
    e e e e e e f 3 3 f e e e e e e 
    e e e e e f e e e e f e e e e e 
    e e e e e e e e e e e e e e e e 
    e e e f e e e e e e e e f e e e 
    e e e e f f f f f f f f e e e e 
    e e e e e e e e e e e e e e e e 
    e e e e e e e e e e e e e e e e 
    `, SpriteKind.Enemy)
myHammer = sprites.create(img`
    .................44.............
    ...............4422ee...........
    ...............4422ee...........
    .............4422eeeeee.........
    .............4422eeeeee.........
    ...........4422eeeeeeeeee.......
    ...........4422eeeeeeeeee.......
    .........4422eeeeeeeeeeeeee.....
    .........4422eeeeeeeeeeeeee.....
    ...........eeeeeeeeeeeeeeeeee...
    ...........eeeeeeeeeeeeeeeeee...
    .............eeeeeeeeeeeeee8866.
    .............eeeeeeeeeeeeee8866.
    .............ccddeeeeeeee8866...
    .............ccddeeeeeeee8866...
    ...........ccddbbeeeeee8866.....
    ...........ccddbbeeeeee8866.....
    .........ccddbb....ee8866.......
    .........ccddbb....ee8866.......
    .......ccddbb........66.........
    .......ccddbb........66.........
    .....ccddbb.....................
    .....ccddbb.....................
    ...ccddbb.......................
    ...ccddbb.......................
    .ccddbb.........................
    .ccddbb.........................
    .ddbb...........................
    .ddbb...........................
    ................................
    ................................
    ................................
    `, SpriteKind.Player)
simplified.moveOnlyOnscreenWithArrows(myHammer, simplified.Speeds.Fast)
carnival.startCountdownGame(15, carnival.WinTypes.Multi)
carnival.addLabelTo("Whack-the-Mole", carnival.Areas.Bottom)
game.showLongText("Player 1: Use the arrow keys to move the hammer. Player 2: Press B to move the mole.", DialogLayout.Center)
game.onUpdateInterval(1000, function () {
    simplified.checkMoleEscape(mp.playerSelector(mp.PlayerNumber.Two), 1)
})
